---
title: Home
---
{% include "src/partials/header.html" %}
<div class="header_full">
  <a href="/games">
  <img src="/img/header/head-spectral.png" class="header_img" alt="Spectral Robot Task Force" />
  <div class="header_text">
    <header>Spectral Robot Task Force</header>
    <summary>A multiplayer turn-based strategy game with robot ghosts fighting werewolves.</summary>
  </div>
  </a>
</div>

<hr>

<div class="game_list">
  <div class="subgame">
    <a href="/games">
    <img src="/img/thumb/game/spectral.png" class="subgame_img" alt="Games" />
    <h2 class="subgame_header">Games</h2></a>
    <p class="subgame_text">Check out the awesome games I designed and programmed, often in collaboration with amazing people.</p>
  </div>

  <div class="subgame">
    <a href="/websites">
    <img src="/img/thumb/website/statsatlast.png" class="subgame_img" alt="Websites" />
    <h2 class="subgame_header">Websites</h2></a>
    <p class="subgame_text">I've built many websites for businesses and professionals.</p>
  </div>

  <div class="subgame">
    <a href="/resume">
    <img src="/img/me/danieljost5.png" class="subgame_img" alt="Resume" />
    <h2 class="subgame_header">Résumé</h2></a>
    <p class="subgame_text">See my experience in game programming, team management, and web development.</p>
  </div>
</div>
{% include "src/partials/footer.html" %}
